# Generated by Django 4.1.7 on 2023-08-28 22:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kuruluş Adı')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Kuruluş Logo')),
                ('org_type', models.CharField(choices=[('IND', 'Şahıs'), ('LARGE', 'Büyük işletme'), ('SME', 'KOBİ'), ('NGO', 'STK')], max_length=5, verbose_name='Kuruluş Türü')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Ülke')),
                ('foundation_date', models.DateField(verbose_name='Kuruluş Tarihi')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Çalışan Sayısı')),
            ],
        ),
    ]
