# Generated by Django 4.1.7 on 2023-08-28 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(related_name='followed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
